### PR TITLE
Fixed relative paths

### PR DESCRIPTION
**Pull request by nelak**
This should show how to accomplish the relative paths.
Ideally it should be supported better when universal webpack is released.
You can check zeit's issues for more reference.

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
wow, cool, thanks)

**Comment by BjornMelgaard** [comment]
Hi, @nelak , can you help? `_document.tsx` is omitted by next and rendered as 
```
'use strict';

module.exports = require('next/dist/server/document.js');
```

P.S. new version pushed, im truing to integrate styled-components

**Comment by BjornMelgaard** [comment]
I think its related to this error 
```
 ✘  ~/projects/nextjs-typescript-boilerplate   master ●  yrl
yarn run v0.28.4
$ tslint --type-check -c tslint.json -p tsconfig.json '{app,pages}/*.{ts,tsx}'

Invalid source file: pages/_document.tsx. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by nelak** [comment]
@BjornMelgaard I'll take a look at it when I have time, this is something that may be doable, but I won't know until I try.

**Pull request merged**
